# Generated by Django 5.2.7 on 2025-10-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='my_images'),
        ),
    ]
