# Generated by Django 5.2.7 on 2025-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_story',
            field=models.TextField(),
        ),
    ]
